apps/inventario/urls.py
from django.urls import path, include
from . import views as viewsi

app_name= "inventario"
urlpatterns = [

    path('crear/impresora', viewsi.CrearImpresora.as_view(), name="crear_impresora"  ),
    path('lista/impresoras', viewsi.ListaImpresoras.as_view(), name="lista_impresoras"  ),
    path('editar/impresora/<int:pk>', viewsi.UpdateImpresora.as_view(), name="editar_impresora"  ),
    path('crear/papel', viewsi.CrearPapel.as_view(), name="crear_papel"  ),
    path('lista/papel', viewsi.ListaPapeles.as_view(), name="lista_papeles"  ),
    path('editar/papel/<int:pk>', viewsi.UpdatePapel.as_view(), name="editar_papel"  ),




]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.cotizacion.views import PagPrincipal
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),
    path('usuario/',include('apps.usuario.urls', namespace='usuario')),
    path('cotizacion/', include('apps.cotizacion.urls', namespace='cotizacion')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('', PagPrincipal.as_view(),name='inicio'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),



]

apps/inventario/models.py
from django.db import models

# Create your models here.


class Impresora(models.Model):
    nombre = models.CharField(max_length=20, null=True, blank=True )
    tiempo_pre= models.IntegerField()
    largo_rodillo= models.IntegerField()
    velocidad_imp= models.IntegerField()
    def __str__(self):
        return '{} '.format(self.nombre)
    class Meta:

        ordering = ['-id']

class Papel(models.Model):
    nombre=models.CharField(max_length=50)
    costo= models.IntegerField()
    def __str__(self):
        return '{}'.format(self.nombre)
    class Meta:

        ordering = ['-id']

apps/inventario/forms.py
from django import forms
from .models import Impresora, Papel


class ImpresoraForm(forms.ModelForm):

    class Meta:
        model = Impresora

        fields = [
        'nombre',
        'tiempo_pre',
        'largo_rodillo',
        'velocidad_imp',



        ]
        labels = {

                'nombre': ' Referencia de impresora',
                'tiempo_pre': 'Tiempo de preparacion ',
                'largo_rodillo': 'Largo del rodillo ' ,
                'velocidad_imp':  'Velocidad de impresion ' ,


        }
        widgets= {

                'nombre': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Referencia' }  )  ,
                'tiempo_pre': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Horas' }  )  ,
                'largo_rodillo':   forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Pulgadas'}  ) ,
                'velocidad_imp':  forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Pulgadas/Minuto'}  ),

        }

class PapelForm(forms.ModelForm):

    class Meta:
        model = Papel

        fields   = [
        'nombre',
        'costo',




        ]
        labels = {

                'nombre': ' Referencia ',
                'costo': 'Costo ',



        }
        widgets= {

                'nombre': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Referencia' }  )  ,
                'costo': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Pesos/m2' }  )  ,


        }

apps/inventario/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Impresora, Papel
from .forms import ImpresoraForm, PapelForm

# Create your views here.
class CrearImpresora(CreateView):
	model= Impresora
	template_name="crear_impresora.html"
	context_object_name = 'obj'
	form_class= ImpresoraForm
	success_url= reverse_lazy("inicio")
	#success_message=" Registrado"

class ListaImpresoras(ListView):
    model = Impresora
    template_name="lista_impresora.html"


class CrearPapel(CreateView):
	model= Impresora
	template_name="crear_papel.html"
	context_object_name = 'obj'
	form_class= PapelForm
	success_url= reverse_lazy("inventario:lista_papeles")
	#success_message=" Registrado"

class ListaPapeles(ListView):
    model = Papel
    template_name="lista_papel.html"


class UpdateImpresora(UpdateView):
	model= Impresora
	template_name="editar_papel.html"
	context_object_name = 'obj'
	form_class= ImpresoraForm
	success_url= reverse_lazy("inventario:lista_impresoras")

class UpdatePapel(UpdateView):
	model= Papel
	template_name="editar_papel.html"
	context_object_name = 'obj'
	form_class= PapelForm
	success_url= reverse_lazy("inventario:lista_papeles")

apps/inventario/templates/crear_impresora.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:crear_impresora' %}" >

            <div class="col-xl-12 col-md-12 mb-12">

                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                              Nueva impresora
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                          <br>
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>

                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

apps/inventario/templates/crear_papel.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:crear_papel' %}" >

            <div class="col-xl-12 col-md-12 mb-12">

                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                              Nuevo tipo de papel
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                          <br>
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>

                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

apps/inventario/templates/editar_papel.html
{% extends 'base.html' %}






{% block content %}


<div class="container">


<ul>

</ul>
<h4> COMPLETE LA INFORMACION  </h4>


<form method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button class="btn btn-primary "type="submit">Guardar</button>
</form>

</div>



{% endblock %}

apps/inventario/templates/lista_impresora.html
{% extends 'base.html' %}

{% block content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Impresoras </h6>

  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not object_list %}
    <div class="alert alert-info">No Hay Impresoras Registradas</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success"  id="btnnewmimp" href="#"><i class="far fa-calendar-plus"></i> Nueva impresora</a>
    </div>

    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
          <th data-sortable="true" data-field="id">No.</th>
          <th data-sortable="true" data-field="nombre">Nombre </th>
          <th data-sortable="true" data-field="tiempo_pre">Tiempo Preparacion </th>
          <th data-sortable="true" data-field="largo_rodillo">Largo de rodillo </th>
              <th data-sortable="true" data-field="velocidad_imp">Velocidad de impresion </th>

          <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% if object_list %}
    		{% for usuario in object_list %}
    		<tr>
    			<td>{{ usuario.id }}</td>
    			<td>{{ usuario.nombre }}</td>
    			<td>{{ usuario.tiempo_pre }} horas</td>
          	<td>{{ usuario.largo_rodillo }} in</td>
          <td>{{ usuario.velocidad_imp }} in/min </td>

    			<td>
            <a class="btn btn-primary"  href="{% url 'inventario:editar_impresora' usuario.id %}"> Editar </a>
    			</td>
    		</tr>
    		{% endfor %}

    		{% else %}
    		<h1> </h1>
    		{% endif %}
      </tbody>

    </table>
  </div>
</div>


<script type="text/javascript">


       $("#btnnewmimp").click(function(e){

                  abrir_modal("{% url 'inventario:crear_impresora' %}");


               });



</script>



{% endblock %}

apps/inventario/templates/lista_papel.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Tipos de papel </h6>

  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not object_list %}
    <div class="alert alert-info">No hay tipos de papel registrados </div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success"  id="btnnewpaper" href="#"><i class="far fa-calendar-plus"></i> Nuevo tipo de papel </a>
    </div>

    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
          <th data-sortable="true" data-field="id">No.</th>
          <th data-sortable="true" data-field="nombre">Nombre </th>
          <th data-sortable="true" data-field="costo">Costo  </th>

          <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% if object_list %}
    		{% for usuario in object_list %}
    		<tr>
    			<td>{{ usuario.id }}</td>
    			<td>{{ usuario.nombre }}</td>
    			<td>{{ usuario.costo|intcomma }} Pesos/m2</td>


    			<td>
            <a class="btn btn-primary" href="{% url 'inventario:editar_papel' usuario.id %}"> Editar </a>
    			</td>
    		</tr>
    		{% endfor %}

    		{% else %}
    		<h1> </h1>
    		{% endif %}
      </tbody>

    </table>
  </div>
</div>


<script type="text/javascript">


       $("#btnnewpaper").click(function(e){

                  abrir_modal("{% url 'inventario:crear_papel' %}");


               });


</script>



{% endblock %}