apps/cotizacion/urls.py
from django.urls import path, include
from . import views as viewsc

app_name= "cotizacion"
urlpatterns = [

    path('crear/<int:pk>', viewsc.CrearCotizacion.as_view(), name="crear"  ),
    path('lista/cotizaciones', viewsc.ListaCotizacion.as_view(), name="lista_cotizaciones"  ),
    path('editar/<int:pk>', viewsc.UpdateCotizacion.as_view(), name="editar"  ),


]

apps/inventario/urls.py
from django.urls import path, include
from . import views as viewsi

app_name= "inventario"
urlpatterns = [

    path('crear/impresora', viewsi.CrearImpresora.as_view(), name="crear_impresora"  ),
    path('lista/impresoras', viewsi.ListaImpresoras.as_view(), name="lista_impresoras"  ),
    path('editar/impresora/<int:pk>', viewsi.UpdateImpresora.as_view(), name="editar_impresora"  ),
    path('crear/papel', viewsi.CrearPapel.as_view(), name="crear_papel"  ),
    path('lista/papel', viewsi.ListaPapeles.as_view(), name="lista_papeles"  ),
    path('editar/papel/<int:pk>', viewsi.UpdatePapel.as_view(), name="editar_papel"  ),




]

apps/usuario/urls.py
from django.urls import path, include
from . import views as viewsu

app_name= "usuario"
urlpatterns = [

    path('lista', viewsu.ListaUsuarios.as_view() , name='lista'),
    path('nuevo', viewsu.CrearUsuario.as_view() , name='nuevo'),



]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.cotizacion.views import PagPrincipal
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),
    path('usuario/',include('apps.usuario.urls', namespace='usuario')),
    path('cotizacion/', include('apps.cotizacion.urls', namespace='cotizacion')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('', PagPrincipal.as_view(),name='inicio'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),



]

apps/cotizacion/models.py
from django.db import models
from apps.usuario.models import Cliente
from apps.inventario.models import Impresora, Papel
# Create your models here.


class Cotizacion(models.Model):
    cliente= models.ForeignKey(Cliente,on_delete=models.CASCADE)
    notintas=models.IntegerField()
    ancho=models.FloatField(default=0)
    largo=models.FloatField(default=0)
    modos_impresion=(('a lo largo','a lo largo'),('a lo ancho','a lo ancho'))
    area= models.FloatField(null=True,blank=True)
    modo_impresion= models.CharField(choices=modos_impresion,default="a lo largo",max_length=12,blank=False,null=False)
    tiempo_impresion= models.DecimalField(default=0,max_digits=9, decimal_places=3)
    tipos_impresion=(('Digital','Digital'),('Flexografica','Flexografica'))
    tipo_impresion=models.CharField(choices=tipos_impresion,default="Digital",max_length=12,blank=False,null=False)
    maquina_impresion= models.ForeignKey(Impresora,on_delete=models.CASCADE, blank=False)
    tipo_papel= models.ForeignKey(Papel,on_delete=models.CASCADE, blank= False )

    noetiquetas= models.IntegerField( blank=False)
    costo_operador= models.IntegerField(null=True)

    porc_utilidad= models.IntegerField( blank=False)
    porc_desperdicio= models.DecimalField(default=0,max_digits=9, decimal_places=3)
    costo= models.DecimalField(default=0,max_digits=9, decimal_places=3)
    class Meta:
        verbose_name_plural = "Clientes"
        ordering = ['-id']

    def save(self,*args, **kwargs):
        papel= Papel.objects.get(id=self.tipo_papel_id)
        impresora= Impresora.objects.get(id=self.maquina_impresion_id)
        self.area= self.ancho*self.largo
        print(self.tiempo_impresion)
        if self.modo_impresion=="a lo largo":
            arriba_etiqueta=self.largo
            arriba_etiqueta_inicial=self.largo
            abajo_etiqueta=self.ancho
            abajo_etiqueta_inicial=self.ancho
            print("LARGO")

        else:
            arriba_etiqueta=self.ancho
            arriba_etiqueta_inicial=self.ancho
            abajo_etiqueta=self.largo
            abajo_etiqueta_inicial=self.largo
            print("ANCHO")

        n=0
        p=0

        while impresora.largo_rodillo > arriba_etiqueta:
            n+=1
            arriba_etiqueta=arriba_etiqueta_inicial*n
            
            if impresora.largo_rodillo<= arriba_etiqueta:

                break
            else:
                continue


        ancho_etiquetas=arriba_etiqueta_inicial*n

        print("ancho_etiquetas",ancho_etiquetas)

        desperdicio_ancho=  impresora.largo_rodillo- ancho_etiquetas

        print("numero de etiqueta",n)
        print("desperdicio ancho",desperdicio_ancho)
        for i in range(0,self.noetiquetas,n):
            p+=1
            print(p)

        print("abajo_etiqueta_inicial",abajo_etiqueta_inicial)

        largo_papel=abajo_etiqueta_inicial*p
        etiquetas_barrido=p*n
        print("largo_papel",largo_papel)
        print("n",n)
        desperdicio_etiquetas=(etiquetas_barrido-self.noetiquetas)*self.area
        desperdicio_area= desperdicio_ancho*largo_papel
        desperdicio_total= desperdicio_etiquetas+desperdicio_area
        print("noetiquetas",self.noetiquetas)



        print("desperdicio_etiquetas",desperdicio_etiquetas)


        self.porc_desperdicio=desperdicio_total

        self.tiempo_impresion=((largo_papel*(1/39.37))/impresora.velocidad_imp)


        if self.tipo_impresion=="Digital":
            self.costo= ((self.largo*self.ancho*(1/1550.0031))*self.noetiquetas*papel.costo) + (self.tiempo_impresion*self.costo_operador)
            self.costo = (self.costo*(self.porc_utilidad/100)+self.costo)
        else:
            area=(self.largo*self.ancho*(1/1550.0031))
            self.costo= ((area + desperdicio_area )*self.noetiquetas*papel.costo) + (impresora.tiempo_pre*self.costo_operador*self.notintas) +(self.tiempo_impresion*self.costo_operador)

        return super(Cotizacion, self).save( *args, **kwargs)

apps/cotizacion/forms.py
from django import forms
from .models import Cotizacion


class CotizacionForm(forms.ModelForm):

    class Meta:
        model = Cotizacion

        fields = [
        'cliente',
        'notintas',
        'ancho',
        'largo',
        'tipo_impresion' ,
        'maquina_impresion' ,
        'modo_impresion',
        'tipo_papel' ,
        'noetiquetas',
        'costo_operador',
        'porc_utilidad',
        'porc_desperdicio',
        'costo',


        ]
        labels = {

                'cliente': 'Cliente',
                'notintas': ' Numero  de tintas',
                'ancho':  'Ancho',
                'largo':   'Largo',
                'tipo_impresion': 'Tipo de impresión',
                'maquina_impresion': 'Tipo de Maquina de impresión',
                'modo_impresion': 'Modo de impresion',
                'tipo_papel': 'Tipo de Papel',
                'noetiquetas': 'Numero de etiquetas',
                'costo_operador': 'Costo del operador ',
                'porc_utilidad': 'Porcentaje de utilidad',
                'porc_desperdicio': 'Desperdicio',
                'costo': 'Costo',


        }
        widgets= {


                'cliente': forms.Select(attrs= {'class': 'form-control'}  )  ,
                'notintas': forms.TextInput(attrs= {'class': 'form-control'}  )  ,
                'ancho': forms.TextInput(attrs= {'class': 'form-control', 'placeholder':'in' }  )  ,
                'largo': forms.TextInput(attrs= {'class': 'form-control', 'placeholder':'in'}  )  ,
                'maquina_impresion': forms.Select(attrs= {'class': 'form-control'}  )  ,
                'modo_impresion': forms.Select(attrs= {'class': 'form-control'}  )  ,
                'tipo_impresion': forms.Select(attrs= {'class': 'form-control'}  )  ,
                'tipo_papel': forms.Select(attrs= {'class': 'form-control'}  )  ,
                'noetiquetas': forms.TextInput(attrs= {'class': 'form-control'}  )  ,
                'costo_operador': forms.TextInput(attrs= {'class': 'form-control', 'placeholder':'Pesos/Hora' }  )  ,
                'porc_utilidad': forms.TextInput(attrs= {'class': 'form-control','placeholder':'%'}  )  ,
                'porc_desperdicio': forms.TextInput(attrs= {'class': 'form-control','placeholder':'Pulgadas','readonly': True}  )  ,
                'costo': forms.TextInput(attrs= {'class': 'form-control', 'readonly': True}  )  ,

        }

apps/cotizacion/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Cotizacion
from .forms import CotizacionForm


# Create your views here.


class PagPrincipal(TemplateView):

	template_name="base.html"

class CrearCotizacion(CreateView):
	model=Cotizacion
	template_name="registro_cotizacion.html"
	context_object_name = 'obj'
	form_class= CotizacionForm
	success_url= reverse_lazy("inicio")
	#success_message=" Registrado"
	def get_initial(self):
		initial = super().get_initial()
		initial['cliente'] = self.kwargs['pk']
		return initial

class ListaCotizacion(ListView):
	model= Cotizacion
	template_name="lista_cotizacion.html"


class UpdateCotizacion(UpdateView):
	model = Cotizacion
	template_name = 'registro_cotizacion.html'
	form_class = CotizacionForm
	success_url = reverse_lazy('cotizacion:lista_cotizaciones')

apps/cotizacion/templates/lista_cotizacion.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de cotizaciones </h6>

  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not object_list %}
    <div class="alert alert-info">No Hay Cotizaciones Registradas</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success" href="{% url 'usuario:lista' %}"><i class="far fa-calendar-plus"></i> Lista de usuarios </a>
    </div>

    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
          <th data-sortable="true" data-field="id">No.</th>
          <th data-sortable="true" data-field="cliente">Nombre </th>
          <th data-sortable="true" data-field="area">Area de etiqueta </th>
          <th data-sortable="true" data-field="tipo_impresion">Tipo de impresión</th>
          <th data-sortable="true" data-field="maquina_impresion"> Impresora </th>
          <th data-sortable="true" data-field="tiempo_impresion"> Tiempo de impresion</th>
          <th data-sortable="true" data-field="tipo_papel"> Papel </th>
          <th data-sortable="true" data-field="noetiquetas"> # de etiquetas </th>
          <th data-sortable="true" data-field="porc_utilidad">Utilidad </th>
          <th data-sortable="true" data-field="porc_desperdicio">Desperdicio </th>
          <th data-sortable="true" data-field="costo"> Costo </th>
          <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% if object_list %}
    		{% for usuario in object_list %}
    		<tr>
    			<td>{{ usuario.id }}</td>
    			<td>{{ usuario.cliente.nombre }} {{ usuario.cliente.apellido }}</td>
          	<td>{{ usuario.area }} in² </td>
    			<td>{{ usuario.tipo_impresion }} </td>
          <td>{{ usuario.maquina_impresion }} </td>
          <td>{{ usuario.tiempo_impresion  }} h </td>
          <td>{{ usuario.tipo_papel }} </td>
          <td>{{ usuario.noetiquetas }} </td>
          <td>{{ usuario.porc_utilidad }} % </td>
          <td>{{ usuario.porc_desperdicio }} in² </td>
          <td>$ {{ usuario.costo|intcomma }} </td>

    			<td>
            <a class="btn btn-primary" href="{% url 'cotizacion:editar' usuario.id %}"> Editar </a>
    			</td>
    		</tr>
    		{% endfor %}

    		{% else %}
    		<h1> </h1>
    		{% endif %}
      </tbody>

    </table>
  </div>
</div>


<script type="text/javascript">


       $("#btnnewmimp").click(function(e){

                  abrir_modal("{% url 'inventario:crear_impresora' %}");


               });


</script>



{% endblock %}

apps/cotizacion/templates/registro_cotizacion.html
{% extends 'base.html' %}






{% block content %}


<div class="container">


<ul>

</ul>
<h4> COMPLETE LA INFORMACION  </h4>


<form method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button class="btn btn-primary "type="submit">Guardar</button>
</form>

</div>



{% endblock %}