apps/cotizacion/urls.py
from django.urls import path, include
from . import views as viewsc

app_name= "cotizacion"
urlpatterns = [

    path('crear/<int:pk>', viewsc.CrearCotizacion.as_view(), name="crear"  ),
    path('lista/cotizaciones', viewsc.ListaCotizacion.as_view(), name="lista_cotizaciones"  ),
    path('editar/<int:pk>', viewsc.UpdateCotizacion.as_view(), name="editar"  ),


]

apps/usuario/urls.py
from django.urls import path, include
from . import views as viewsu

app_name= "usuario"
urlpatterns = [

    path('lista', viewsu.ListaUsuarios.as_view() , name='lista'),
    path('nuevo', viewsu.CrearUsuario.as_view() , name='nuevo'),



]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.cotizacion.views import PagPrincipal
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),
    path('usuario/',include('apps.usuario.urls', namespace='usuario')),
    path('cotizacion/', include('apps.cotizacion.urls', namespace='cotizacion')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('', PagPrincipal.as_view(),name='inicio'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),



]

apps/usuario/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    NAT='Natural'
    JUR='Jurídica'
    TIPO_CLIENTE = [
        (NAT,'Natural'),
        (JUR,'Jurídica')
    ]
    nombre=models.CharField(max_length=50, null=True, blank=True)

    apellido= models.CharField(max_length=50, null=True, blank=True)
    cc= models.CharField(max_length=12, null=False,blank=False)
    n_cel= models.CharField(max_length=10, null=False,blank=False)
    tipo=models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=NAT
    )

    def __str__(self):
        return '{} {}'.format(self.apellido,self.nombre)


    class Meta:
        verbose_name_plural = "Clientes"
        ordering = ['-id']

apps/usuario/forms.py
from django import forms
from .models import Cliente


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente

        fields = [
        'tipo',
        'nombre',
        'apellido',
        'cc' ,
        'n_cel' ,

        ]
        labels = {
                'tipo': 'Tipo de Cliente',
                'nombre': 'Nombre' ,
                'apellido':  'Apellidos' ,
                'cc': 'Numero de Cedula o Nit' ,

        }

        widgets= {
                'tipo': forms.Select(attrs= {'class': 'form-control'}  )  ,
                'nombre': forms.TextInput(attrs= {'class': 'form-control'}  )  ,
                'apellido':   forms.TextInput(attrs= {'class': 'form-control'}  ) ,
                'cc':  forms.TextInput(attrs= {'class': 'form-control'}  ),
                'n_cel':  forms.TextInput(attrs= {'class': 'form-control'}  ),

        }

apps/usuario/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Cliente
from .forms import ClienteForm

class CrearUsuario(CreateView):
    model = Cliente
    template_name = "crear_usuario.html"
    form_class = ClienteForm
    success_url= reverse_lazy('inicio')

class ListaUsuarios(ListView):
    model = Cliente
    template_name="lista_usuarios.html"

apps/usuario/templates/crear_usuario.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        <form method="POST" role="form" class="form-inline" action="{% url 'usuario:nuevo' %}" >

            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">

                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>

                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

apps/usuario/templates/lista_usuarios.html
{% extends 'base.html' %}

{% block content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Usuarios </h6>

  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not object_list %}
    <div class="alert alert-info">No Hay Usuarios </div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success" onclick="#" id="btn_newclient" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
    </div>

    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
          <th data-sortable="true" data-field="id">No.</th>
          <th data-sortable="true" data-field="nombre">Nombre </th>
          <th data-sortable="true" data-field="apellido">Apellido </th>
          <th data-sortable="true" data-field="tipo">Tipo de cliente </th>
          <th data-sortable="true" data-field="cc">Numero de cedula </th>
          <th data-sortable="true" data-field="n_cel">Numero de celular </th>

          <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% if object_list %}
    		{% for usuario in object_list %}
    		<tr>
    			<td>{{ usuario.id }}</td>
    			<td>{{ usuario.nombre }}</td>
    			<td>{{ usuario.apellido }}</td>
          <td>{{ usuario.tipo }}</td>
          <td>{{ usuario.cc }}</td>
          <td>{{ usuario.n_cel }}</td>

    			<td>
            <a class="btn btn-primary" href="{% url 'cotizacion:crear' usuario.id %}"> Cotización </a>
    			</td>

    		</tr>
    		{% endfor %}

    		{% else %}
    		<h1> </h1>
    		{% endif %}
      </tbody>

    </table>
  </div>
</div>


<script type="text/javascript">


$("#btn_newclient").click(function(e){

 abrir_modal("{% url 'usuario:nuevo' %}");

   });




</script>



{% endblock %}